name: Deploy Website to Spaceship

on:
  push:
    branches:
      - main  # আপনার গিটহাবের মেইন ব্রাঞ্চের নাম যদি master হয়, তবে এখানে master লিখে দিবেন

jobs:
  web-deploy:
    name: 🎉 Deploying Files
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 🚀 Sync Files to Spaceship
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
